# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb347e97340f62dd020555eab8b15ac446d14ce01dbf17706921b07814b4ff51b543557d69dbb7a72c6236a063f68e82324b0f5fdc2ee44c8561871c4d771c5b

test:
  secret_key_base: 5b96e1b2f87f3750e0bf886ebc245d12092a7dd960d38390fa83d022aebf6e1257b78f13edacd70d08abe1a165336bb2859509d23eb560bc23ac09798e032cee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
