        # PRODUCTION
Sympol.create!([
    {name: "Triquetra", origin: "Celtic", description: "Latin meaning 'threecornered' It's a holy symbol, and it's meanings are many. It varies in its aspects of spirit, nature, being-ness, and of the cosmos. This trinity symbol, as most others, reflects core concepts such as: Mind, Body, Spirit. Afterlife, Underworld, Physical life. Tribe, Country, Deity (god/goddess). These are just a few trinities folded within this Celtic symbol meaning. There are many more. The differences lay in the intent of the symbol, and the tribe that was using at the time in Celtic history. The negative space in the center of this symbol symbolizes the center of all influences. In personal ritual, it could represent the self at the center of trinity influences. In a tribe, the center is the heart of the people with the three elements creating an unbreakable union."},
    {name: "Triskele", origin: "Celtic", description: "This is another trinity symbol often found among ancient Celtic relics. It is sometimes referred to as a triskelion. The terms are often considered synonymous. This Celtic symbol meaning deals with the drawing of the three powers of maiden, mother and crone. It is often considered a sign of female power and especially power through transition and growth. This, however, is not an exclusive definition. Sometimes the symbol represents religious aspects of Father, Son, Holy Ghost. This representation came much later amongst Celtic descendants who were exposed to Christian conversion. In any instance, this trinity symbol can represent a triangle of foundational necessity. Meaning - you cannot have a healthy whole without all three elements joined together. Hence: Mind, Body, Spirit. Sun, Moon, Earth. Light, Dark, Gloaming (twilight). Not one energy can exist without the others."},
    {name: "Awen", origin: "Celtic", description: "This is the three rays, or three flames symbol - also known as the Awen. The first and third rays in this symbol represent male and female energy (respectively). The middle ray represents the balance of both energies. At its heart, this symbol expresses the constant theme of the trinity. Threes are a massive influence amongst the Celtic people. Mostly, because it is clear there cannot be balance, or a whole unit without the union of three core energies. For example: Male, Female, Offspring. God, Goddess, (Hu)Man. Creating, Destroying, Sustaining. Past, Present, Future. The ancient Celts used the Awen as a symbol for transformation experienced through the power of fire. If the Celtic Awen symbol could speak, it might say: 'I was a certain entity. Fire burned and changed me. Now I am completely transformed.'"},
    {name: "Celtic Cross", origin: "Celtic", description: "As one of the most common Celtic symbols, the Celtic cross is of significant cultural and religious importance. There are many theories regarding the origin of the symbol although none of them could be (and possibly never will be) confirmed. The most common theory suggests that Saint Patrick (or Saint Declan) created the symbol to convert pagans/the Druids. Realizing the importance of the sun and its life-giving power to pagans, Saint Patrick decided to combine the Christian cross with the Celtic circle representing eternity."},
    {name: "Claddagh", origin: "Celtic", description: "The meaning of the claddagh ring is what gives the ring it's significance. Over the years the cladagh ring has brought up designs with minor variations, the basic meaning and significance of the Irish claddagh ring has however been retained. The hands of the ring are shown holding the heart and the hands denote friendship and togetherness, the heart itself signifies love and the crown in the claddagh ring stands for loyalty. It is this meaning of the claddagh rings that make them an ideal choice for all occassions, wedding rings, birth stone rings, engagement rings, mothers day rings and rings for just about any other occassion. The deep and true meaning of the Irish claddagh rings has also put them into a group of rings referred to as the faith rings. In today's materialistic world where love, friendship and loyalty are becoming increasingly rarer by the day, the claddagh ring with it's realistic and worthy meaning makes an ideal gift to give and to receive."},
    {name: "Carolingian Cross", origin: "Celtic", description: "Made of four triquetrae/triquetras, Carolingian cross is a symbol most commonly used by the Carolingian Dynasty of France (the dynasty of Charlemagne / Charles the Great ). It represents unity, balance and the eternity of God."},
    {name: "Tree of Life", origin: "Celtic", description: "Crann Bethadh, the Celtic Tree of Life, is much more than a single trunk borne of roots below and stretching to the heavens with branches above; it is the symbol of all of life on the planet, born of the earth and sustained by the power of the Universe. There is no better depiction of the intimate and unbreakable bonds between each of us and the natural world in which we live than the Tree of Life knot. It is an intricate representation that links every root below to every branch above, depicting the network of natural bonds that links all Life together."},
    {name: "Eternity Knot", origin: "Celtic", description: "The Eternity Knot - could be any of the celtic knot design patterns that has a closed path. It means that such Celtic knots neither have a beginning, nor an end. George Bain, a Celtic art teacher from Scotland attributed this meaning to the eternity knot."},
    {name: "st. Bridig's Cross", origin: "Celtic", description: "The Saint Brigid’s cross is a custom that marks the feast day of St. Brigid, which falls on the 1st of February, the beginning of spring. The making of the cross has many meanings and stories; one ritual is that the cross is hung over the door as a way of protecting the household from evil spirits and energies. Another tradition that is practiced is that a new cross is made each year on St. Brigid's day, and the old one hanging from the year before is then burned to keep fire from the household."},
    {name: "Celtic Harp", origin: "Celtic", description: "The traditional symbol of Ireland, the harp is said to reflect the immortality of the soul. The musicians of ancient chieftains played the harp, and it remains one of the most popular Celtic instruments today. You’ll find the harp everywhere in Ireland, from coins, uniforms and the state seal to the Guinness pint glass."},
    {name: "Bythol", origin: "Celtic", description: "This Celtic symbol, formed from two triskeles was created by jewelry makers to symbolizes everlasting love. They are said to represent two people joined together forever in body, mind and spirit."},
    {name: "Shamrock", origin: "Celtic", description: "The shamrock is a single-stemmed plant growing on the hills of Ireland. St. Patrick, the Patron Saint of Ireland made the shamrock famous and today you can find the symbol on t-shirts, postcards, stamps and many other different things. The Celts believed that everything important in the world came in threes; the three dominions of earth, sky and sea, the three ages of man, and phases of the moon. A plant with three leaves would have been held in high regard."},
    {name: "Celtic Hounds", origin: "Celtic", description: "The Celtic hounds were dogs well respected by royalty and warriors. They were given as gifts to men of honour and many warriors and chiefs took the name as a title to show their loyalty and courage."},
    {name: "Celtic Salmon", origin: "Celtic", description: "The Salmon of Knowledge (Irish: bradán feasa) is a creature figuring in the Fenian Cycle of Celtic mythology. (It is sometimes identified with Fintan mac Bóchra, who was known as 'The bushman' and was once transformed into a salmon.)"},
    {name: "Sheela", origin: "Celtic", description: "The Sheela-na-gig is a shocking, immediately noticeable figure found in Celtic medieval stonework. Sheela is most commonly depicted as a squat, ugly female creature using her hands to display grotesquely large genitals. Sheelas of various ages adorn stone steles all over the Irish countryside ; they are also found in the intricate carvings in cathedrals and stone churches in ireland, England, and throughout Europe, often in tandem with the Green man. Sheela is very likely related to the ancient Celtic Goddess; her images are much older than the churches they often appear in, suggesting they are elements of much older religious sites. Many closely resemble ancient Viking figures of a creator goddess Ormgudinna."},
    {name: "Cerne Abbas Giant", origin: "Celtic", description: "This gigantic chalk earthwork is formally known as the Cerne Abbas Giant, but is best known by the moniker “rude man,” in reference to his gigantic genitalia. The figure can be found carved into chalk bedrock on a hillside in Dorset, England."},
    {name: "Cernunnos", origin: "Celtic", description: "Cernunnos is the mysterious horned deity worshipped by Iron age Celts across Europe until the end of the first century. Very little is known about Cernunnos except his name and his image, which appears on numerous stone carvings and other religious artifacts throughout Europe. He appears crowned with stag’s antlers, often seated in a meditative position, and is almost always depicted with images of wild game animals. His Celtic name is unknown, although he may be associated with Derg Corra, the early Celtic “Man in the Tree.” He may also be related to the Celtic god Fionn (Finn MacCuill), who had a close affinity with deer."},
    {name: "", origin: "Celtic", description: "The Green Man is a mysterious, eerie figure depicted mainly in medieval European stonework, believed to represent an ancient vegetation deity. The Greenman is nearly always depicted as a “foliate head,” that is, a face made of leaves and vines. Sometimes, it appears as a human face peering out from leaves, other times, with animal features."},
    {name: "Celtic Bull", origin: "Celtic", description: "The bull was an important part of Druid sacrificial rituals, especially those of a prophetic nature. The bull was the emblem of the mysterious god Esus (“Lord”)- monuments to the god are frequently inscribed with the Tarvos Trigaranus,(Latin, “bull with three cranes”) an image of a bull or bull’s head with three cranes either perched atop his back or in the branches of a nearby tree. The theft of the bull Donn Cualnge is central to the best know Celtic mythological tale, the Tain bo Cualnge, or “Cattle raid of Cooley,” wherein a prize bull is warred over."},
    {name: "Celtic Boar", origin: "Celtic", description: "celtic bullThe bull was an important part of Druid sacrificial rituals, especially those of a prophetic nature. The bull was the emblem of the mysterious god Esus (“Lord”)- monuments to the god are frequently inscribed with the Tarvos Trigaranus,(Latin, “bull with three cranes”) an image of a bull or bull’s head with three cranes either perched atop his back or in the branches of a nearby tree. The theft of the bull Donn Cualnge is central to the best know Celtic mythological tale, the Tain bo Cualnge, or “Cattle raid of Cooley,” wherein a prize bull is warred over."},
    {name: "Celtic Serpent", origin: "Celtic", description: "The Celtic serpent were ancient symbols of fertility, wisdom, and immortality. A hybrid horned dragon/snake figure was connected to the torque collar, a symbol of kingship and status, and to the horned deity Cernunnos. The serpent was related to the dragon, and was connected with healing pools and springs. The Romans observed that the Druids especially revered the serpent for healing, and that they ascribed the same powers to the “serpent’s egg,” a particular sort of egg-shaped stone. A number of old tales feature magical treasure-guarding serpents who reside in wells- a common motif is the horned snake who guards a golden torque, a reference to divine authority."},
    {name: "Celtic Dragon", origin: "Celtic", description: "The dragon represents the untamed forces of nature, and often dwelt deep within the earth or sea. A red protector dragon has been a symbol of Wales for more than a thousand years, and dragons of various sorts featured heavily in late heroic tales, especially those of the exploits of Merlin. After the advent of Christianity, the dragon was more likely to symbolize chaos, and many tales of the saints pit the holy men against rampaging dragons who cause natural disasters, stories in which the dragons are not too subtle analogies of the pagan religions- Christians who came to evangelize the Druids took the sacred serpents as sure signs that the Druids were devil worshipers."},
    {name: "Celtic Snake", origin: "Celtic", description: "Since a snake sheds his skin, this can be a symbol of rebirth, an awakening or renewal of oneself. The snake is also said to be a symbol of the search for balance, fertility and transformation."},
    {name: "Celtic Deer", origin: "Celtic", description: "The deer was arguably the most important animal to the early Celts. Before agriculture or animal husbandry; venison was a staple food. Some of the oldest surviving examples of pre-Celtic Neolithic art depicts shape-shifting shamans in the form of deer, who may prefigure the shape-shifting gods and heroes of Celtic legend, as well as Cernunnos, the stag-horned deity of healing and plenty."},
    {name: "Celtic Raven", origin: "Celtic", description: "The Raven Because of their dark coloring and gruesome dietary habits, ravens were emblems war and death, and sacred to the gods and goddesses of the battlefield, most notably the warrior-god Bran and the war-goddess Morrigan. The raven acted as psychopomp, tasked with escorting the souls of the dead into the Otherworld. The ravens were sometimes viewed as the reincarnation of slain warriors and heroes."},
    {name: "Celtic Swan", origin: "Celtic", description: "The swan was revered by the earliest Celts who associated them with the sun, bearers of the chariot of the sun god. Numerous Celtic legends involve magical maidens who transform into swans; these are identifiable through the magical chains of precious metal they wear. Perhaps the most famous Celtic swan-tale is of the children of Lir , the Irish sea-god, whose children are magically transformed into swans by their jealous stepmother. Many Celtic goddesses could likewise shape-shift into swan form;the swan was the sacred bird of Angus, the Irish god of love."},
    {name: "Celtic Crane", origin: "Celtic", description: "The crane was sacred to early Celts, who left behind many votive images of the bird. Manannan Mac Lir, the Irish god of the sea, who had a magical bag made from the the skin of a crane who was his lover magically transformed. The underworld god Midir owned three cranes to guard his home, and to see three cranes is an omen of death. The crane was also an emblem of envy, and Irish legend has many stories of women transformed into cranes by rivals. The crane also features in Christian legends, where transformation into a crane is a common punishment for disrespecting a saint or as penance for a variety of sins."},
    {name: "Celtic Arrow", origin: "Celtic", description: "This symbolized that the Celtic warriors were the 'brothers of the arrow'. It was considered an honor for the Celts to be a part of a fierce battle, and risk their lives for victory. The Celtic arrows symbolized the power to pierce the life of the enemy. The arrow was also the symbolic representation of the sun, as the sun pierces through darkness and defeats it. Therefore, the design was like a sun pierced with an arrow. The arrow also symbolized the virility of the warriors."},
    {name: "Griffin", origin: "Celtic", description: "The Griffin symbolizes the strength and fierce mythical creature, which is believed to have the upper body (head, wings, and talons) of an eagle, and the lower body and tail of a lion. These creatures did not only look fierce but were also known to be impossible to defeat due to the characteristics that they possessed, sharp like an eagle and strong like a lion."},
    {name: "Celtic Horse", origin: "Celtic", description: "The Celtics had a horse-goddess named Epona. She was considered to be the goddess of victory over enemies. Another reason why this animal was a symbolic representation of strength to the Celtics was the fact that a horse that provided speed, aggression, strength, and dominance over the opponent. They believed that painting the image of the horse gave them the same qualities as this animal , and the blessings of Epona. All this, meant a closer step to a victorious win in the battle war."},

    {name: "Adinkrahene", origin: "Adinkra", description: '"Chief of the adinkra symbols" - symbol of greatness, charisma and leadership. This symbol is said to have played an inspiring role in the designing of other symbols. it signifies the importance of playing a leadership role.'},
    {name: 'Akoben', origin: 'Adinkra', description: '"war horn" - symbol of vigilance and wariness. Akoben is a horn used to sound a battle cry.'},
    {name: 'Akofena', origin: 'Adinkra', description: '"sword of war " - symbol of courage, valor, and heroism - The crossed swords were a popular motif in the heraldic shields of many former Akan states. In addition to recognizing courage and valor, the swords can represent legitimate state authority.'},
    {name: 'Akoko Nan', origin: 'Adinkra', description: '"the leg of a hen" - symbol of nurturing and discipline. The full name of this symbol translates to "The hen treads on her chicks, but she does not kill them." This represents the ideal nature of parents, being both protective and corrective. An exhortation to nurture children, but a warning not to pamper them.'},
    {name: 'Akoma', origin: 'Adinkra', description: '"the heart" - symbol of patience and tolerance. According to Agbo, when a person is said to "have a heart in his stomach," that person is very tolerant.'},
    {name: 'Akoma Ntoso', origin: 'Adinkra', description: '"linked hearts" - symbol of understanding and agreement'},
    {name: 'Ananse Ntontan', origin: 'Adinkra', description: '"spiders web" - symbol of wisdom, creativity and the complexities of life. Ananse, the spider, is a well-known character in African folktales.'},
    {name: 'Asase Ye Duru', origin: 'Adinkra', description: '"the Earth has weight" - symbol of providence and the divinity of Mother Earth. This symbol represents the importance of the Earth in sustaining life.'},
    {name: 'Aya', origin: 'Adinkra', description: '"fern" - symbol of endurance and resourcefulness. The fern is a hardy plant that can grow in difficult places. "An individual who wears this symbol suggests that he has endured many adversities and outlasted much difficulty." (Willis, The Adinkra Dictionary)'},
    {name: 'Bese Saka', origin: 'Adinkra', description: '"sack of cola nuts" - symbol of affluence, power, abundance, plenty, togetherness and unity The cola nut played an important role in the economic life of Ghana. A widely-used cash crop, it is closely associated with affluence and abundance. This symbol also represents the role of agriculture and trade in bringing peoples together.'},
    {name: 'Bi Nka Bi', origin: 'Adinkra', description: '"No one should bite the other" - symbol of peace and harmony. This symbol cautions against provocation and strife. The image is based on two fish biting each other tails.'},
    {name: 'Boa Me Na Me Mmoa Wo', origin: 'Adinkra', description: '"Help me and let me help you" - symbol of cooperation and interdependence'},
    {name: 'Dame-Dame', origin: 'Adinkra', description: 'symbol of intelligence and ingenuity'},
    {name: 'Duafe', origin: 'Adinkra', description: '"wooden comb" - symbol of beauty and cleanliness; symbols of desirable feminine qualities. The meaning of this symbol is characterized slightly differently in "The Adinkra Dictionary" and "The Values of Adinkra Symbols"; the former emphasizes more abstract qualities of feminine goodness, love and care, while the latter has a more literal interpretation, looking ones best and good hygiene. In any case, the duafe was a prized possession of the Akan woman, used to comb and plait her hair.'},
    {name: 'Dwennimmen', origin: 'Adinkra', description: '"rams horns" - symbol of humility together with strength. The ram will fight fiercely against an adversary, but it also submits humbly to slaughter, emphasizing that even the strong need to be humble.'},
    {name: 'Eban', origin: 'Adinkra', description: '"fence" - symbol of love, safety and security. The home to the Akan is a special place. A home which has a fence around it is considered to be an ideal residence. The fence symbolically separates and secures the family from the outside. Because of the security and the protection that a fence affords, the symbol is also associated with the security and safety one finds in love.'},
    {name: 'Epa', origin: 'Adinkra', description: '"handcuffs" - symbol of law and justice, slavery and captivity. Adolph Agbo, in "Values of Adinkra Symbols" notes that handcuffs were introduced in Africa as a result of the slave trade, and later became popular among chiefs in cuffing offenders of the law. "The symbol reminds offenders of the uncompromising nature of the law. It however discourages all forms of slavery."'},
    {name: 'Ese Ne Tekrema', origin: 'Adinkra', description: '"the teeth and the tongue" - symbol of friendship and interdependence. The teeth and the tongue play interdependent roles in the mouth. They may come into conflict, but they need to work together.'},
    {name: 'Fawohodie', origin: 'Adinkra', description: '"independence" - symbol of independence, freedom, emancipation."From the expression: Fawodhodie ene obre na enam. Literal translation: Independence comes with its responsibilities.'},
    {name: 'Fihankra', origin: 'Adinkra', description: '"house/compound" - symbol of security and safety. Typical of Akan (Asante) architecture, the communal housing compound has only one entrance and exit.'},
    {name: 'Fofo', origin: 'Adinkra', description: '"yellow flowered plant" - symbol of jealousy and envy. When the fofos petals drop, they turn into black spiky-like seeds. The Akan liken the nature of this plant to a jealous person.'},
    {name: 'Funtunfunefu-Denkyemfunefu', origin: 'Adinkra', description: '"Siamese crocodiles" - symbol of democracy and unity. The Siamese crocodiles share one stomach, yet they fight over food. This popular symbol is a remind that infighting and tribalism is harmful to all who engage in it.'},
    {name: 'Gye Nyame', origin: 'Adinkra', description: '"except for God" - symbol of the supremacy of God. This unique and beautiful symbol is ubiquitous in Ghana. It is by far the most popular for use in decoration, a reflection on the deeply religious character of the Ghanaian people.'},
    {name: 'Hwe Mu Dua', origin: 'Adinkra', description: '"measuring stick" - symbol of examination and quality control. This symbol stresses the need to strive for the best quality, whether in production of goods or in human endeavors.'},
    {name: 'Hye Won Hye', origin: 'Adinkra', description: '"that which does not burn" - symbol of imperishability and endurance. This symbol gets its meaning from traditional priests that were able to walk on fire without burning their feet, an inspiration to others to endure and overcome difficulties.'},
    {name: 'Kete Pa', origin: 'Adinkra', description: '"good bed" - symbol of a good marriage. From the expression that a woman who has a good marriage is said to sleep on a good bed.'},
    {name: 'Kintinkantan', origin: 'Adinkra', description: '"puffed up extravagance" - symbol of arrogance'},
    {name: 'Kwatakye Atiko', origin: 'Adinkra', description: '"hair style of an Asante war captain" - symbol of bravery and valor. "This symbols is said to be a special hair style of Kwatakye, a war captain of old Asante. The symbol has come to represent bravery and fearlessness. It is also given as an earned title to any brave son of an Akan community."'},
    {name: 'Mate Masie', origin: 'Adinkra', description: '"What I hear, I keep" - symbol of wisdom, knowledge and prudence. The implied meaning of the phrase "mate masie" is "I understand". Understanding means wisdom and knowledge, but it also represents the prudence of taking into consideration what another person has said.'},
    {name: 'Me Ware Wo', origin: 'Adinkra', description: '"I shall marry you" - symbol of commitment, perseverance. From the expression "No one rushes into the job of mixing the concrete for building the house of marriage."'},
    {name: 'Mframadan', origin: 'Adinkra', description: '"wind-resistant house" - symbol of fortitude and readiness to face lifes vicissitudes. This symbol suggests a reinforced or well-built home -- one built to withstand windy and treacherous conditions. It reflects in Asante history a clause in the unwritten constitutution of the Golden Stool. Oral acocunts say that according to that clause, mud houses in Kumasi must be reinforced with turf. This reinforcing would cause the house to be sturdier and resistant to unfavorable weather conditions.'},
    {name: 'Mmere Dane', origin: 'Adinkra', description: '"time changes" - symbol of change, lifes dynamics'},
    {name: 'Mmusuyidee', origin: 'Adinkra', description: '"that which removes bad luck" - symbol of good furtune and sanctity'},
    {name: 'Mpatapo', origin: 'Adinkra', description: '"knot of pacification/reconciliation" - symbol of reconciliation, peacemaking and pacification. Mpatapo represents the bond or knot that binds parties in a dispute to a peaceful, harmonious reconciliation. It is a symbol of peacemaking after strife.'},
    {name: 'Mpuannum', origin: 'Adinkra', description: '"five tufts (of hair)" - symbol of priestly office, loyalty and adroitness. This symbol is said to be the hairstyle of joy. It is the traditional hairstyle of the priestesses. The design of the adinkra symbol mpuannum resembles the way the priestesses hair was tied. It also represents the devotion and faithfulness one displays when doing a task required of one. In addition, mpuannum means loyalty or the embodiment of lofty duty to a desired goal.'},
    {name: 'Nea Onnim No Sua A Ohu', origin: 'Adinkra', description: '"He who does not know can know from learning" - symbol of knowledge, life-long education and continued quest for knowledge'},
    {name: 'Nea Ope Se Obedi Hene', origin: 'Adinkra', description: '"he who wants to be king" - symbol of service and leadership. From the expression "Nea ope se obedi hene daakye no, firi ase sue som ansa" meaning "He who wants to be king in the future must first learn to serve."'},
    {name: 'Nkonsonkonson', origin: 'Adinkra', description: '"chain link" - symbol of unity and human relations. A reminder to contribute to the community, that in unity lies strength'},
    {name: 'Nyame Dua', origin: 'Adinkra', description: '"tree of god – altar" - symbol of Gods presence and protection. The Nyame Dua is a sacred spot where rituals are performed. Erected in front of the house or compound, it is crafted from a tree that has been cut where three or more branches come together. This stake holds an earthenware vessell filled with water and herbs or other symbolic materials for purification and blessing rituals.'},
    {name: 'Nkyimu', origin: 'Adinkra', description: '"the crossed divisions made on adinkra cloth before stamping" - symbol of skillfulness, precision. Before adinkra cloth is stamped with the symbols, the artisan blocks off the cloth with lines in a rectangular grid using a broad-tooth comb. This preparation is symbolic of the exacting technique which results in the highest quality product.'},
    {name: 'Nkyinkyim', origin: 'Adinkra', description: '"twisting" - symbol of initiative, dynamism and versatility.'},
    {name: 'Nsaa', origin: 'Adinkra', description: '"a type of hand-woven fabric" - symbol of excellence, genuineness, authenticity. According to "The Adinkra Dictionary" by W. Bruce Willis, the nsaa symbols reflects a saying: "nea onnim nsaa oto nago", which he translates as "He who does not know authentic Nsaa will buy the fakes."'},
    {name: 'Nsoromma', origin: 'Adinkra', description: '"child of the heavens" - symbol of guardianship. A reminder that God is the father and watches over all people.'},
    {name: 'Nyame Biribi Wo Sori', origin: 'Adinkra', description: '"God is in the heavens" - symbol of hope. A reminder that Gods dwelling place is in the heaven, where he can listen to all prayers. This signifies the immortality of mans soul, believed to be a part of God. Because the soul rests with God after death, it cannot die.'},
    {name: 'Nyame Nnwu Na Mawu', origin: 'Adinkra', description: '"God never dies, therefore I cannot die" - symbol of Gods omnipresence and the perpetual existence of mans spirit. This signifies the immortality of mans soul, believed to be a part of God. Because the soul rests with God after death, it cannot die.'},
    {name: 'Nyame Ye Ohene', origin: 'Adinkra', description: '"God is King" - symbol of majesty and supremacy of God.'},
    {name: 'Nyansapo', origin: 'Adinkra', description: '"wisdom knot" - symbol of wisdom, ingenuity, intelligence and patience. An especially revered symbol of the Akan, this symbol conveys the idea that "a wise person has the capacity to choose the best meeans to attain a goal. Being wise implies broad knowledge, learning and experience, and the ability to apply such faculties to practical ends."'},
    {name: 'Odo Nnyew Fie Kwan', origin: 'Adinkra', description: '"Love never loses its way home" - symbol of the power of love.'},
    {name: 'Okodee Mmowere', origin: 'Adinkra', description: '"the talons of the eagle" - symbol of strength, bravery, power. The eagle is the mightiest bird in the sky, and its strength is concentrated in its talons. The Oyoko clan, one of the nine Akan clans, uses this symbol as their clan emblem.'},
    {name: 'Onyankopon Adom Nti Biribiara Beye Yie', origin: 'Adinkra', description: '"By Gods grace, all will be well" - symbol of hope, providence, faith'},
    {name: 'Osram Ne Nsoromma', origin: 'Adinkra', description: '"The Moon and the Star" - symbol of love, faithfulness, harmony. This symbol reflects the harmony that exists in the bonding between a man and a woman.'},
    {name: 'Owo Foro Adobe', origin: 'Adinkra', description: '"snake climbing the raffia tree" - symbol of steadfastness, prudence and diligence. Because of its thorns, the raffia tree is a very dangerous challenge to the snake. His ability to climb it is a model of persistence and prudence.'},
    {name: 'Owuo Atedee', origin: 'Adinkra', description: '"the ladder of death" - symbol of mortality. a reminder of the transitory nature of existence in this world and of the imperative to live a good life to be a worthy soul in the afterlife.'},
    {name: 'Pempamsie', origin: 'Adinkra', description: '"sew in readiness" - symbol of readiness, steadfastness, hardiness. The design of this symbol resembles the links of a chain, and implies strength through unity as well as the importance of being prepared.'},
    {name: 'Sankofa', origin: 'Adinkra', description: '"return and get it" - symbol of importance of learning from the past'},
    {name: 'Sesa Wo Suban', origin: 'Adinkra', description: '"Change or transform your character" - symbol of life transformation. This symbol combines two separate adinkra symbols, the "Morning Star" which can mean a new start to the day, placed inside the wheel, representing rotation or independent movement. '},
    {name: 'Tamfo Bebre', origin: 'Adinkra', description: '"the enemy will stew in his own juice" - symbol of jealousy and envy.'},
    {name: 'Wawa Aba', origin: 'Adinkra', description: '"seed of the wawa tree" - symbol of hardiness, toughness and perseverance. The seed of the wawa tree is extremely hard. In Akan culture, it is a symbol of someone who is strong and tough. It inspires the individual to persevere through hardship.'},
    {name: 'Woforo Dua Pa A', origin: 'Adinkra', description: '"when you climb a good tree" - symbol of support, cooperation and encouragement. From the expression "Woforo dua pa a, na yepia wo" meaning "When you climb a good tree, you are given a push". More metaphorically, it means that when you work for a good cause, you will get support.'},
    {name: 'Wo Nsa Da Mu A', origin: 'Adinkra', description: '"If your hands are in the dish" - symbol of participatory government, democracy and pluralism. From the aphorism, "Wo nsa da mu a, wonni nnya wo" -- "If your hands are in the dish, people do not eat everything and leave you nothing."'},
  {name: "Knot of Inanna", origin: "Assyrian", description: "The Knot of Inanna is a stylized bundle of reeds, an emblem of the Babylonian goddess Inanna. This symbol was early written form of the name of the goddess, whose name was composed of two characters, the post and the ring of rushes. It is related to the tyet knot of Isis. As a symbol of divine authority, it is the ancestor of the crozier, a staff carried by Catholic bishops."},

  {name: "Winged Sun Disk", origin: "Assyrian", description: "The winged disk emblem is found in many ancient cultures around the world. The winged sun disk is one of the oldest religious symbols on earth, and it is invariably a solar symbol. An Assyrian winged disk represents the sun God Shamash."},
  {name: "Star of Ishtar", origin: "Assyrian", description: "A symbol of the Mesopotamian Goddess Ishtar (Anath, Astarte, Inanna). The eight points represent the movements of the planet Venus associated with this Goddess, and the eight gates of the city of Babylon."},
  {name: "Tanit", origin: "Assyrian", description: "This symbol is found on many ancient stone carvings, and represents the Goddess Tanit. Tanit was the Carthaginian and Phoenician Goddess of the moon. Tanit was the Patron of Carthage and the consort of the god Baal. She may have been related to the goddess Astarte/Ishtar."},
  {name: "Shamash", origin: "Assyrian", description: "A common symbol of the ancient Assyrian/Mesopotamian Sun God Shamash. It is often referred to as the “Seal of Shamash,” and appears near images of the God, or to represent his presence when worn by Kings or in inscriptions. The Seal of Shamash is a typical solar symbol, and probably represents the Sun Wheel, or solar calendar, much like the Celtic Cross or the Pueblo Zia. The four arms most likely represent the solstices and equinoxes, which were extremely important calendar days in ancient agrarian cultures."},
  {name: "Faravahar", origin: "Assyrian", description: "The Farohar or faravahar is both an emblem of the Zoroastrian religion and of Persian identity.  Faravahar means “to choose.” The Faravahar is descended from the Egyptian winged disk, a symbol of divine kingship. It once represented the Assyrian sun god Shamash, and may have represented the corona of a solar eclipse."},
  {name: "Adar", origin: "Assyrian", description: " The Adar is the sacred fire of the Zoroastrians (Parsis). The fire symbolizes purity, the essence of life, and the presence of God. In the Zoroastrian creation story, fire is the last creation, but brings life to all that came before it. It is a similar concept to the Ruach ha Elohim, (Holy Spirit) in the Hebrew scriptures. The sacred flame is presided over by Asha Vahista (“Holiest Truth,”) one of the Amesha Spentas or “bounteous immortals,” divine beings similar to Archangels. "},
  {name: "Babylonian Tree of Life", origin: "Assyrian", description: "This image represents the early Mesopotamian Tree of Life. In Babylonian mythology, the Tree of Life was a magical tree that grew in the center of paradise. The Apsu, or primordial waters, flowed from its roots. It is the prototype of the tree described in Genesis: the biblical Tree of Paradise evolved directly from this ancient symbol; it is the symbol from which the Egyptian, Islamic, and Kabbalistic Tree of Life concepts originated."},
  {name: "Senmurgh", origin: "Assyrian", description: "The Simurgh is an ancient, immortal Persian mythological beast similar to a griffin or Phoenix. It is most often described as having the head and foreparts of a dog, the wings and tail of a peacock, and a body covered with scales. The Simurg is associated with the Tree of Life and present in many old tales of the creation. He is benevolent, protective guardian figure with healing powers."},
  {name: "Cherubim", origin: "Assyrian", description: "The Cherubim were originally the ancient protectors of the Mesopotamian Tree of Life. They were often depicted supporting the thrones of deities and kings.They are closely related to (and often identical to) the sphinx. In the Judeo-Christian tradition, they are the four vast, winged creatures described in the visions of Ezekiel, each winged creature bearing four faces: a lion, a bull, eagle, and human head."},
  {name: "Tiamat", origin: "Assyrian", description: "Tiamat (“Sea,” in Akkadian) was the ancient Sumero-Babylonian personification of the primordial salt waters of chaos. With her consort Apsu, the ‘sweet’ water, Tiamat mothered the first generation of the gods. Tiamat took the form of a gigantic winged dragon, whose body was split in two by the hero Marduk to create the heavens and the firmament: her upper body became the vault of heaven; the lower, the earth; her blood, the oceans."},
  {name: "Kulullu", origin: "Assyrian", description: "This figure was known to the Assyrians as Kullulû, meaning “fish man.” The kullulu was a guardian figure, a dweller of the sacred Absu, the watery underground domain of the God Ea. Figures of the fish-man were often concealed in the construction of buildings to serve as protective charms. From about the fourth century, the figure was associated (probably erroneously) with the god Dagan (meaning “grain”), most commonly known by his Hebrew name, Dagon. Dagan was a vegetation god, the father of the god Baal, the mythological creator of the plow. Dagon is mentioned several times in the Hebrew scriptures, where he is associated with the Philistines. It is to Dagon’s temple that the Ark of the Covenant is taken after being captured from the Hebrews; the next morning, they discover the statue of the god lying on the floor, sans head and hands."},

  {name: "Ankh", origin: "Egyptian", description: "The ankh is the most well-known symbol to come out of ancient Egypt. In their hieroglyphic system of writing the ankh represents the concept of eternal life, and that is the general meaning of the symbol."},
  {name: "Was", origin: "Egyptian", description: "The was symbol represented a ceremonial staff and was often displayed in connection with the ankh. The was staff is often seen in the hands of various gods, particularly Anubis and Set. The crooked top of the staff mirrors the strange animal shape of Set's own head. A physical was bears the carved head of this animal. The was staff was a symbol of power and rulership, as ceremonial staffs and scepters generally are."},
  {name: "Eye of Horus", origin: "Egyptian", description: "After the ankh symbol, the icon commonly called the Eye of Horus is the next most well known. It consists of a stylized eye and eyebrow. Two lines extend from the bottom of the eye, possibly to mimic the facial markings on a falcon local to Egypt, as Horus's symbol was a falcon. In fact, three different names are applied to this symbol: the eye of Horus, the eye of Ra, and the Wadjet. These names are based on the meaning behind the symbol, not specifically its construction. Without any context, it is impossible to definitively determine which symbol is meant."},
  {name: "Djed Column", origin: "Egyptian", description: "The djed column as an Egyptian hieroglyph represented stability. It was often displayed artistically in combination with the was staff and the ankh, which created a combined meaning of strength, success, longevity and long life. Because Egyptian culture survived for such an immensely long time – more than two thousand years – it contains many contradictory myths as well as vastly different meanings for various symbols. These evolve over time as old ideas become incorporated into new myths or gods ascending in popularity start taking over aspects of other."},
  {name: "Coptic Cross", origin: "Egyptian", description: "The Coptic cross is a symbol of Coptic Christianity, the primary denomination of Egyptian Christians today. The cross comes in a number of different forms, some of which are obviously influenced by the older, pagan ankh symbol of eternal life."},
  {name: "Modern Coptic Cross", origin:"Egyptian", description: "Old style Coptic crosses bear a clear influence from the Egyptian Ankh. However, modern Coptic crosses have largely lost that influence. Rather, they are equal-armed crosses which may or may not have a circle within or behind the center-point of the symbol."},
  {name: "Tiet", origin: "Egyptian", description: "Tiet/Tyet, also known as the Knot of Isis and the Blood of Isis, is an Egyptian symbol that looks a lot like the ankh symbol. Its meaning was also interpreted to be similar to the ankh. It is assumed to symbolize life. It was generally identified with goddess Isis and mostly used with the ankh and Djed Pillar of Osiris which is why it was interpreted the dual nature of life. There is no accurate information or valid suggestion regarding the name the Blood of Isis but it is assumed to be given to Tiet for it represented the menstrual blood of Isis and the magical powers it gave."},
  {name: "Ka", origin: "Egyptian", description: "Ka symbol in one of the most complex Egyptian symbols used in hieroglyphics. That is because it represented three different spiritual concepts. Ka was the symbol of receiving life from other men and gods in addition to being the source of these powers and the spiritual double of every living men."},
  {name: "Ba", origin: "Egyptian", description: "Shaped as a bird (mostly a falcon) with a human head, the Ba symbol was shown as leaving or entering someone’s tomb or beside his mummified body. The word “Ba” might be interpreted as “soul” or “spirit” although “spiritual manifestation” would be a more accurate translation. That is because Ba is known as a part of the soul in ancient Egyptian belief. More specifically, Ba was believed to be the unique character of an object. This comes close to the meaning of “personality” for the lack of a better word. According to this belief, even an inanimate object could have Ba."},
  {name: "Feather of Maat", origin: "Egyptian", description: "The Feather of Maat/Ma’at is one of the most common Egyptian symbols used in hieroglyphics. Goddess Maat represented justice in Egyptian culture and the Feather of Maat can be seen within the context of “ensuring justice” in ancient inscriptions. That is because ancient Egyptians  believed that one’s heart would be weighed against the Feather of Maat in the Hall of Two Truths when his soul entered Duat (the Underworld). If his heart was found to be equal to or lighter than this would mean he was a virtuous person and he would go to Aaru (paradise ruled by Osiris). If not, then his heart would be eaten by Ammit, the soul-eating goddess and he would be cursed to remain in the Underworld forever."},
  {name: "Deshret", origin: "Egyptian", description: "Deshret, also known as the Red Crown of Egypt, is the symbol that represents Lower Egypt, the lands of goddess Wadjet. It is also used as the symbol of Kemet, the fertile lands within the territory of Set."},
  {name: "Shen Ring", origin: "Egyptian", description: "Shen is the coiled circle or cartouche symbol in ancient Egyptian culture which represents divinity. It was mostly used in Mesopotamia and Egypt. The symbol, which had the shape of a circle originally, was sometimes used as a cartouche. This kind of use aimed to represent divine protection. That is to say, the person whose name was written inside the Shen symbol, mostly a king or royalty, was under divine protection according to the belief."},
  {name: "Uraeus", origin: "Egyptian", description: "Derived from the word “iaret” meaning “the risen one”, Uraeus is a significant ancient Egyptian symbol that is made of a rising cobra. Uraeus symbol represented the connection between gods and kings/pharaohs and the pharaohs were recognized with the Uraeus symbol they wore. Uraeus also symbolized the absolute authority and power of the gods and the pharaohs. It was believed to give magical powers and ensure magical protection to the wearer."},
  {name: "Seba", origin: "Egyptian", description: "Seba was the star symbol in ancient Egyptian culture and it represented the star-gods or constellations. In Egyptian mythology, stars were called as “the followers of Osiris” since they were identified with the souls of the dead in Duat, the Underworld. When it is drawn within a circle, the Seba symbol represents Duat."},
  {name: "Hekha and Nekhakha", origin: "Egyptian", description: "The shepherd’s crook symbol in ancient Egyptian culture was the symbol of the state’s power over its people. The word “hekha (HqA)”, which is also an epithet of Osiris, means “to rule”. In a similar way, the flail (nekhakha) was considered as the symbol of royal power. Renowned Egyptologist Toby Wilkinson suggested that the flail symbol represented a king’s coercive power and control over his subjects."},
  {name: "Primordial Hill", origin: "Egyptian", description: "The primordial hill symbol seen in Egyptian inscriptions is among one of the oldest symbols that were used. Egyptians believed that this hill created lands during the chaotic process of creation. It is believed to have inspired the idea of building pyramids."},
  {name: "Menat", origin: "Egyptian", description: "Associated closely with Hathor and Ihy, her son, Menat was known as the symbol of goddess Hathor. In fact, “the Great Menat” was one of Hathor’s names. The Menat symbol represented life, fertility, birth, rebirth, potency and joy. Egyptians wore menat amulets hoping it would bring prosperity, fertility and fortune."},
  {name: "Akhet", origin: "Egyptian", description: "This symbol represents the horizon from which the sun emerged and disappeared. The horizon thus embodied the idea of both sunrise and sunset. It is similar to the two peaks of the Djew or mountain symbol with solar disk in the center. Both the beginning and the end of each day was guarded by Aker, a double lion god. In the New Kingdom, Harmakhet ('Horus in the Horizon') became the god of the rising and setting sun. He was pictured as a falcon, or as a sphinx with the body of a lion. The Great Sphinx of Giza is an example of 'Horus in the Horizon'."},
  {name: "Sekhem", origin: "Egyptian", description: "Egyptian symbol of authority. "},


  {name: "Caduceus", origin: "Greek", description: "The caduceus (☤; pron.: /kəˈdjuːsiːəs/ or /kəˈdjuːʃəs/; from Greek κηρύκειον kērukeion 'heralds staff' ) is the staff carried by Hermes in Greek mythology."},
  {name: "Chi Rho", origin: "Greek", description: "The Chi Rho is one of the earliest forms of christogram, and is used by some Christians. It is formed by superimposing the first two (capital) letters chi and rho (ΧΡ) of the Greek word 'ΧΡΙΣΤΟΣ' =Christ in such a way to produce the monogram. Although not technically a Christian cross, the Chi-Rho invokes the crucifixion of Jesus, as well as symbolizing his status as the Christ."},
  {name: "Dove", origin: "Greek", description: "With its pure white feathers, softly rounded body and gentle demeanor, the dove is one of the most ubiquitous symbols of peace, innocence and purity. On the other hand, the dove’s symbolism is considerably more complex than notions such as these, and in some cases those complexities can prove quite surprising."},
  {name: "Labyrinth", origin: "Greek", description: "In Greek mythology, the Labyrinth was an elaborate structure designed and built by the legendary artificer Daedalus for King Minos of Crete at Knossos. Its function was to hold the Minotaur eventually killed by the hero Theseus. Daedalus had so cunningly made the Labyrinth that he could barely escape it after he built it."},
  {name: "Ouroboros", origin: "Greek", description: "The Ouroboros is a Greek symbol of a snake eating its own tail. This symbol represents infinity."},
  {name: "Peacock", origin: "Greek", description: "Although indigenous to the Indian sub-continent, the peacock has spread far beyond its native land and acquired symbolic meaning in a number of diverse cultures."},
  {name: "Pi", origin: "Greek", description: "The number pi (symbol: π) /paɪ/ is a mathematical constant that is the ratio of a circle's circumference to its diameter, and is approximately equal to 3.14159."},
  {name: "Psi", origin: "Greek", description: "Psi is the 23rd letter of the Greek alphabet and has a numeric value of 700. In both Classical and Modern Greek, the letter indicates the combination /ps/ (as in English word 'lapse')"},
  {name: "Rod of Asclepius", origin: "Greek", description: "In Greek mythology, the Rod of Asclepius (⚕; sometimes also spelled Asklepios or Aesculapius), also known as the asklepian, is a serpent-entwined rod wielded by the Greek god Asclepius, a deity associated with healing and medicine."},
  {name: "Staff", origin: "Greek", description: "The exact meaning of this symbol is somewhat convoluted, but variations of it have been designated as the 'staff' of a number of ancient deities."},

  {name: "Aquarius", origin: "Zodiac", description: "Aquarius is the eleventh astrological sign in the Zodiac, originating from the constellation Aquarius."},
  {name: "Aries", origin: "Zodiac", description: "Aries /ˈɛəriːz/ (meaning 'ram') is the first astrological sign in the Zodiac, spanning the first 30 degrees of celestial longitude (0°≤ λ <30º), which area the Sun transits, on average, between March 21 to April 20 each year."},
  {name: "Capricorn", origin: "Zodiac", description: "Capricorn is the tenth astrological sign in the Zodiac, originating from the constellation of Capricornus. It spans the 270-300th degree of the zodiac, between 270 and 305.25 degree of celestial longitude. In astrology, Capricorn is considered an introvert sign, an earth sign, and one of the four cardinal signs. Capricorn is ruled by the planet Saturn. In the Tropical zodiac, the Sun transits this area of the zodiac from December 22 to January 20 each year."},
  {name: "Gemini", origin: "Zodiac", description:"Gemini (Gem-en-i.e.) is the third astrological sign in the Zodiac, originating from the constellation of Gemini. In astrology, Gemini is considered a 'masculine', positive (extrovert) sign. It is also considered an air sign, and is one of four mutable signs."},
  {name: "Leo", origin: "Zodiac", description:"Leo is a astrological sign of the zodiac, originating from the constellation of Leo. It spans the 120-150th degree of the Tropical zodiac, between 125.25 and 152.75 degree of celestial longitude, which the Sun transits this area on average between July 23 to August 22 each year."},
  {name: "Libra", origin: "Zodiac", description:"Libra is one of the twelve astrological signs in the Zodiac, originating from the constellation of Libra. It spans the 180-210th degree of the zodiac, between 180 and 207.25 degree of celestial longitude, which the Sun transits this area on average between (northern autumnal equinox) September 23 to October 22 each year."},
  {name: "Pisces", origin: "Zodiac", description:"Pisces (pron.: /ˈpaɪsiːz/, pis'eez; Ancient Greek: Ἰχθύες, 'Ikhthues') is the twelfth astrological sign in the Zodiac, originating from the Pisces constellation. It spans the 330° to 360° of the zodiac, between 332.75° and 360° of celestial longitude, which in the Tropical zodiac the Sun transits this area on average between February 18 to March 20 each year."},
  {name: "Sagittarius", origin: "Zodiac", description:"Sagittarius (Greek: Τοξότης, 'Toxotes', Latin: 'Sagittarius') is the ninth astrological sign, which is associated with the constellation Sagittarius. It spans the 240-270th degree of the zodiac, between 234.75 and 270 degree of celestial longitude, which the Sun transits on average between November 23 to December 20 each year."},
  {name: "Scorpio", origin: "Zodiac", description:"Scorpio (Greek: Σκορπιός, 'Skorpios', Latin: 'Scorpio') is the eighth astrological sign in the Zodiac. It spans the 210-240th degree of the zodiac, between 207.25 and 234.75 degree of celestial longitude, an area which the Sun transits on average between October 23 and November 22 each year, linked to the constellation Scorpius."},
  {name: "Taurus", origin: "Zodiac", description:"Taurus is the second astrological sign in the Zodiac. It spans the 30-60th degree of the zodiac, between 27.25 and 54.75 degree of celestial longitude, which the Sun transits this area on average between April 21 to May 22 each year."},
  {name: "Virgo", origin: "Zodiac", description:"Virgo is the sixth astrological sign in the Zodiac. It spans the 150-180th degree of the zodiac, between 152.75 and 180 degree of celestial longitude, which the Tropical zodiac the Sun transits this area on average between August 23 to September 22 each year. Virgo is also part of the 12 zodiac signs."},
  {name: "Cancer", origin: "Zodiac", description:"Cancer is an astrological sign, which is associated with the constellation Cancer. It spans the 90-120th degree of the zodiac, between 90 and 125.25 degree of celestial longitude, which the Sun transits this area on average between June 22 to July 22 each year."},

{name:"Hah Taew", origin:"Sak Yant", description:"The Sak Yant Hah Taew dates its origin back over 700 years to the ancient Kingdom of Lanna which is now known as Northern Thailand.  The Buddhist Monk credited with the design of the Hah Taew 5 Lines Sak Yant is Kruba Kam of Wat Ton Pin, a Buddhist Temple in Chiang Mai, which unfortunately no longer exists today. Kruba Kam designed the Hah Taew at around the time King Mengrai founded the city of Chiang Mai in 1296. The Sak Yant Hah Taew dates its origin back over 700 years to the ancient Kingdom of Lanna which is now known as Northern Thailand.  The Buddhist Monk credited with the design of the Hah Taew 5 Lines Sak Yant is Kruba Kam of Wat Ton Pin, a Buddhist Temple in Chiang Mai, which unfortunately no longer exists today. Kruba Kam designed the Hah Taew at around the time King Mengrai founded the city of Chiang Mai in 1296. / / 1. The first row prevents unjust punishment and leans in your favor when the area is grey, cleans out unwanted spirits and protects the place you live in.

/ 2. The second row reverses and protects against bad horoscope constellations and bad fortune.

/ 3. The third row protects you from the use of black magic and anyone who tries to put a curse on you.

/ 4. The fourth row energizes your good luck, success and fortune in your future ambitions and life style.

/ 5.The fifth row  is to gain charisma and attraction to the opposite sex. It is also is a boost to the fourth row."},
{name:"Gao Yord", origin:"Sak Yant", description:"The Gao Yord is the “Yant Kru” or Master Yant and is a most sacred Buddhist tattoo with very wide ranging powers of protection and is quite possibly the most important of all the available Sak Yant designs. Many people will choose the Gao Yord as their first Sak Yant because of its universal powers and later add other Sak Yant designs of their choice. The basic design of the Gao Yord represents the nine peaks of the mythical mountain of the Gods, Mount Meru. According to Hindu mythology, Mount Meru is the abode of the Lord Brahma as well as other Deities. In Buddhist mythology, Mount Meru is known as Sumeru."},
{name:"Paed Tidt", origin:"Sak Yant", description:"The Sak Yant design ‘Paed Tidt’ or Eight Direction Yant is a sacred Geometric Yant containing eight Mantras written in 2 concentric circles in the center of the design. The design of the Paed Tidt Yant also incorporates eight representations of the Buddha. These are the groups of 3 ovals each increasing in size from the top. In Thailand, there is a Buddha image, each one in a different pose, for every day of the week. (On Wednesdays there are 2 Buddhas, one for the morning and one for the evening) and these 8 Buddha Images can be seen in many Thai temples, usually surrounding a Chedi.
/
The Paed Tidt Yant will give you protection in whichever direction you are traveling and ward off evil spirits. The script used on the Paed Tidt Yant is an ancient Khmer script known as Khom. The Mantras written in the Paed Tidt Yant and which should be chanted when going out to give further protection are as follows."},
{name:"Hanuman", origin:"Sak Yant", description:"Hanuman is the Hindu mythical Monkey God in the time of Rama and  is invincible and has powers far greater than humans, including the ability to fly. In Thai culture Hanuman leads a monkey army to rid the world of unwanted spirits. His main traits were humility and bravery, he was looked upon as hope for humanity, demonstrating to man that a mortal being can in fact rise above the shallowness of our worldly plain. There are different variations of Sak Yants with Hanuman. It is obtained and used to bestow the wearer with the qualities of protection  from danger as well as becoming fearless in the face of adversity. Hanuman also helps to strengthen self-confidence and can influence people on your behalf. It is also said to help one stay focused and gives the determination needed to see something through to a successful conclusion."},
{name:"Yant Suea", origin:"Sak Yant", description:"Represents power and authority.  The Twin Tiger Sak Yant Tattoo is common among Thai people with dangerous occupations and Muay Thai Fighters.  The Tiger represents strength, power, protection and conviction, as well as authority over ones subordinates."},
{name:"Chat Petch", origin:"Sak Yant", description:"Chat Petch means 'from the sky, high above the earth', and was first designed by one of the most famous Thai Tattoo Master : Ajarn Noo Kanpai. The sacred Mantras are interconnected and represent spiritual values continually flowing like water. It brings balance and peace, both spiritually and artistically. Some of Chat Petch’s mystical powers include inner power and strength, good luck, protection for yourself and your loved ones, management skills, wealth and success in your career."},

])

Trait.create!([
  1  {name: "symmetric"},
  2  {name: "asymmetric"},

  3  {name: "straight"},
  4  {name: "curved"},
  5  {name: "straight and curved"},

  6  {name: "open"},
  7  {name: "closed"},
  8  {name: "open and closed"},

  9 {name: "circle"},
  10 {name: "rectangle"},
  11 {name: "square"},
  12 {name: "spiral"},
  13 {name: "knot"},
  14 {name: "star"},
  15 {name: "cross"},
  26 {name: "triangle"},

  16 {name: "single"},
  17 {name: "double"},
  18 {name: "triple"},
  19 {name: "quadruple (4)"},
  20 {name: "quintuple (5)"},
  21 {name: "sextuple (6)"},
  22 {name: "septuple (7)"},
  23 {name: "octuple (8)"},
  24 {name: "nonuple (9)"},
  25 {name: "decuple (10)"},

])

Image.create!([
    {url: "/images/Celtic/Triquetra.png", sympol_id: 1},
    {url: "/images/Celtic/Triskele.jpg", sympol_id: 2},
    {url: "/images/Celtic/Awen.jpg", sympol_id: 3},
    {url: "/images/Celtic/celtic_cross.jpg", sympol_id: 4},
    {url: "/images/Celtic/claddagh.jpg", sympol_id: 5},
    {url: "/images/Celtic/carolingian_cross.jpg", sympol_id: 6},
    {url: "/images/Celtic/tree_of_life.jpg", sympol_id: 7},
    {url: "/images/Celtic/eternity_knot.jpg", sympol_id: 8},
    {url: "/images/Celtic/st_bridig_cross.jpg", sympol_id: 9},
    {url: "/images/Celtic/harp.jpg", sympol_id: 10},
    {url: "/images/Celtic/bythol.jpg", sympol_id: 11},
    {url: "/images/Celtic/shamrock.png", sympol_id: 12},
    {url: "/images/Celtic/celtic_hounds.png", sympol_id: 13},
    {url: "/images/Celtic/celtic_salmon.jpg", sympol_id: 14},
    {url: "/images/Celtic/cernunnos.jpg", sympol_id: 17},
    {url: "/images/Celtic/celtic_greenman.jpg", sympol_id: 18},
    {url: "/images/Celtic/celtic_bull.png", sympol_id: 19},
    {url: "/images/Celtic/celtic_boar.png", sympol_id: 20},
    {url: "/images/Celtic/celtic_serpent.jpg", sympol_id: 21},
    {url: "/images/Celtic/celtic_dragon.jpg", sympol_id: 22},
    {url: "/images/Celtic/celtic_snake.jpg", sympol_id: 23},
    {url: "/images/Celtic/celtic_deer.jpg", sympol_id: 24},
    {url: "/images/Celtic/celtic_raven.png", sympol_id: 25},
    {url: "/images/Celtic/celtic_swan.png", sympol_id: 26},
    {url: "/images/Celtic/celtic_crane.jpg", sympol_id: 27},
    {url: "/images/Celtic/celtic_arrow.jpg", sympol_id: 28},
    {url: "/images/Celtic/Griffin.jpeg", sympol_id: 29},
    {url: "/images/Celtic/celtic_horse.png", sympol_id: 30},

    {url: "/images/Adinkra/adinkrahene.gif", sympol_id: 31},
    {url: "/images/Adinkra/akoben.gif", sympol_id: 32},
    {url: "/images/Adinkra/akofena.gif", sympol_id: 33},
    {url: "/images/Adinkra/akoko_nan.gif", sympol_id: 34},
    {url: "/images/Adinkra/akoma.gif", sympol_id: 35},
    {url: "/images/Adinkra/akoma_ntoso.gif", sympol_id: 36},
    {url: "/images/Adinkra/ananse_ntotan.gif", sympol_id: 37},
    {url: "/images/Adinkra/asase_ye_duru.gif", sympol_id: 38},
    {url: "/images/Adinkra/aya.gif", sympol_id: 39},
    {url: "/images/Adinkra/bese_saka.gif", sympol_id: 40},
    {url: "/images/Adinkra/bi_nka_bi.gif", sympol_id: 41},
    {url: "/images/Adinkra/BOA_ME_NA_ME_MMOA_WO.gif", sympol_id: 42},
    {url: "/images/Adinkra/dame-dame.gif", sympol_id: 43},
    {url: "/images/Adinkra/duafe.gif", sympol_id: 44},
    {url: "/images/Adinkra/dwennimmen.gif", sympol_id: 45},

    {url: "/images/Adinkra/eban.gif", sympol_id: 46},
    {url: "/images/Adinkra/epa.gif", sympol_id: 47},
    {url: "/images/Adinkra/ESE_NE_TEKREMA.gif", sympol_id: 48},
    {url: "/images/Adinkra/FAWOHODIE.gif", sympol_id: 49},
    {url: "/images/Adinkra/FIHANKRA.gif", sympol_id: 50},
    {url: "/images/Adinkra/fofo.gif", sympol_id: 51},
    {url: "/images/Adinkra/FUNTUNFUNEFU-DENKYEMFUNEFU.gif", sympol_id: 52},
    {url: "/images/Adinkra/GYE_NYAME.gif", sympol_id: 53},
    {url: "/images/Adinkra/HWE_MU_DUA.gif", sympol_id: 54},
    {url: "/images/Adinkra/HYE_WON_HYE.gif", sympol_id: 55},
    {url: "/images/Adinkra/KETE_PA.gif", sympol_id: 56},
    {url: "/images/Adinkra/KINTINKANTAN.gif", sympol_id: 57},
    {url: "/images/Adinkra/KWATAKYE_ATIKO.gif", sympol_id: 58},
    {url: "/images/Adinkra/Mate_Masie.gif", sympol_id: 59},
    {url: "/images/Adinkra/ME_WARE_WO.gif", sympol_id: 60},
    {url: "/images/Adinkra/MFRAMADAN.gif", sympol_id: 61},
    {url: "/images/Adinkra/mmere_dane.gif", sympol_id: 62},
    {url: "/images/Adinkra/MMUSUYIDEE.gif", sympol_id: 63},
    {url: "/images/Adinkra/MPATAPO.gif", sympol_id: 64},
    {url: "/images/Adinkra/MPUANNUM.gif", sympol_id: 65},
    {url: "/images/Adinkra/NEA_ONNIM_NO_SUA_A_OHU.gif", sympol_id: 66},
    {url: "/images/Adinkra/NEA_OPE_SE_OBEDI_HENE.gif", sympol_id: 67},
    {url: "/images/Adinkra/NKONSONKONSON.gif", sympol_id: 68},
    {url: "/images/Adinkra/nyame_dua.gif", sympol_id: 69},
    {url: "/images/Adinkra/NKYIMU.gif", sympol_id: 70},
    {url: "/images/Adinkra/NKYINKYIM.gif", sympol_id: 71},
    {url: "/images/Adinkra/nsaa.gif", sympol_id: 72},
    {url: "/images/Adinkra/NSOROMMA.gif", sympol_id: 73},
    {url: "/images/Adinkra/NYAME_BIRIBI_WO_SORO.gif", sympol_id: 74},
    {url: "/images/Adinkra/NYAME_NNWU_NA_MAWU.gif", sympol_id: 75},
    {url: "/images/Adinkra/NYAME_YE_OHENE.gif", sympol_id: 76},
    {url: "/images/Adinkra/NYANSAPO.gif", sympol_id: 77},
    {url: "/images/Adinkra/Odo_Nnyew_Fie_Kwan.gif", sympol_id: 78},
    {url: "/images/Adinkra/OKODEE_MMOWERE.gif", sympol_id: 79},
    {url: "/images/Adinkra/Onyankopon_Adom_Nti_Biribiara_Beye_Yie.gif", sympol_id: 80},
    {url: "/images/Adinkra/OSRAM_NE_NSOROMMA.gif", sympol_id: 81},
    {url: "/images/Adinkra/OWO_FORO_ADOBE.gif", sympol_id: 82},
    {url: "/images/Adinkra/OWUO_ATWEDEE.gif", sympol_id: 83},
    {url: "/images/Adinkra/PEMPAMSIE.gif", sympol_id: 84},
    {url: "/images/Adinkra/SANKOFA.gif", sympol_id: 85},
    {url: "/images/Adinkra/SESA_WO_SUBAN.gif", sympol_id: 86},
    {url: "/images/Adinkra/TAMFO_BEBRE.gif", sympol_id: 87},
    {url: "/images/Adinkra/WAWA_ABA.gif", sympol_id: 88},
    {url: "/images/Adinkra/WOFORO_DUA_PA_A.gif", sympol_id: 89},
    {url: "/images/Adinkra/WO_NSA_DA_MU_A.gif", sympol_id: 90},

    {url: "/images/Assyrian/knotinanna.jpg", sympol_id: 91},
    {url: "/images/Assyrian/assyrian_winged_disk.jpg", sympol_id: 92},
    {url: "/images/Assyrian/ishtar_seal.jpg", sympol_id: 93},
    {url: "/images/Assyrian/tanit.jpg", sympol_id: 94},
    {url: "/images/Assyrian/shamash.jpg", sympol_id: 95},
    {url: "/images/Assyrian/faravahar.jpg", sympol_id: 96},
    {url: "/images/Assyrian/adar.jpg", sympol_id: 97},
    {url: "/images/Assyrian/Babylonian_Tree_of_Life.jpg", sympol_id: 98},
    {url: "/images/Assyrian/simurgh.jpg", sympol_id: 99},
    {url: "/images/Assyrian/kerub.jpg", sympol_id: 100},
    {url: "/images/Assyrian/tiamat.jpg", sympol_id: 101},
    {url: "/images/Assyrian/kulullu.jpg", sympol_id: 102},

    {url: "/images/Egyptian/ankh.png", sympol_id: 103},
    {url: "/images/Egyptian/was.png", sympol_id: 104},
    {url: "/images/Egyptian/eye_of_horus.png", sympol_id: 105},
    {url: "/images/Egyptian/djec_column.jpg", sympol_id: 106},
    {url: "/images/Egyptian/coptic_cross.png", sympol_id: 107},
    {url: "/images/Egyptian/modern_coptic_cross.jpeg", sympol_id: 108},
    {url: "/images/Egyptian/tiet.jpg", sympol_id: 109},
    {url: "/images/Egyptian/ka.jpg", sympol_id: 110},
    {url: "/images/Egyptian/ba.jpg", sympol_id: 111},
    {url: "/images/Egyptian/feather_of_maat.png", sympol_id: 112},
    {url: "/images/Egyptian/deshret.png", sympol_id: 113},
    {url: "/images/Egyptian/shen_ring.png", sympol_id: 114},
    {url: "/images/Egyptian/uraeus.jpg", sympol_id: 115},
    {url: "/images/Egyptian/seba.png", sympol_id: 116},
    {url: "/images/Egyptian/Hekha_Nekhakha.png", sympol_id: 117},
    {url: "/images/Egyptian/primordial_hill.jpg", sympol_id: 118},
    {url: "/images/Egyptian/menat.jpeg", sympol_id: 119},
    {url: "/images/Egyptian/akhet.png", sympol_id: 120},
    {url: "/images/Egyptian/sekhem.jpg", sympol_id: 121},

    {url: "/images/Greek/Caduceus.png", sympol_id: 122},
    {url: "/images/Greek/Chi_Rho.png", sympol_id: 123},
    {url: "/images/Greek/Dove.png", sympol_id: 124},
    {url: "/images/Greek/Labyrinth.png", sympol_id: 125},
    {url: "/images/Greek/Ouroborus.png", sympol_id: 126},
    {url: "/images/Greek/peacock.png", sympol_id: 127},
    {url: "/images/Greek/Pi.png", sympol_id: 128},
    {url: "/images/Greek/psi.png", sympol_id: 129},
    {url: "/images/Greek/rod_of_asclepius.png", sympol_id: 130},
    {url: "/images/Greek/greek_staff.png", sympol_id: 131},

    {url: "/images/Zodiac/Aquarius.png", sympol_id: 132},
    {url: "/images/Zodiac/Aries.png", sympol_id: 133},
    {url: "/images/Zodiac/Capricorn.png", sympol_id: 134},
    {url: "/images/Zodiac/Gemini.png", sympol_id: 135},
    {url: "/images/Zodiac/Leo.png", sympol_id: 136},
    {url: "/images/Zodiac/Libra.png", sympol_id: 137},
    {url: "/images/Zodiac/Pisces.png", sympol_id: 138},
    {url: "/images/Zodiac/Sagittarius.png", sympol_id: 139},
    {url: "/images/Zodiac/Scorpio.png", sympol_id: 140},
    {url: "/images/Zodiac/Taurus.png", sympol_id: 141},
    {url: "/images/Zodiac/Virgo.png", sympol_id: 142},
    {url: "/images/Zodiac/Cancer.png", sympol_id: 143},

{url: "images/Sak_Yant/hah_taew_.jpg", sympol_id: "144"},
{url: "images/Sak_Yant/gao_yord_one.jpg", sympol_id: "145"},
{url: "images/Sak_Yant/paed_tidt_one.jpg", sympol_id: "146"},
{url: "images/Sak_Yant/hanuman_one.jpg", sympol_id: "147"},
{url: "images/Sak_Yant/Yant_suea.jpg", sympol_id: "148"},
{url: "images/Sak_Yant/chat_petch.jpg", sympol_id: "149"}



])



SympolTrait.create!([

  {sympol_id: 1, trait_id: 1},
  {sympol_id: 1, trait_id: 4},
  {sympol_id: 1, trait_id: 7},
  {sympol_id: 1, trait_id: 13},
  {sympol_id: 1, trait_id: 26},
  {sympol_id: 1, trait_id: 18},

  {sympol_id: 2, trait_id: 2},
  {sympol_id: 2, trait_id: 4},
  {sympol_id: 2, trait_id: 6},
  {sympol_id: 2, trait_id: 12},
  {sympol_id: 2, trait_id: 18},

  {sympol_id: 3, trait_id: 1},
  {sympol_id: 3, trait_id: 5},
  {sympol_id: 3, trait_id: 7},
  {sympol_id: 3, trait_id: 9},
  {sympol_id: 3, trait_id: 16},
  {sympol_id: 3, trait_id: 18},

  {sympol_id: 4, trait_id: 2},
  {sympol_id: 4, trait_id: 5},
  {sympol_id: 4, trait_id: 7},
  {sympol_id: 4, trait_id: 15},
  {sympol_id: 4, trait_id: 16},

  {sympol_id: 5, trait_id: 1},
  {sympol_id: 5, trait_id: 4},
  {sympol_id: 5, trait_id: 7},

  {sympol_id: 6, trait_id: 1},
  {sympol_id: 6, trait_id: 4},
  {sympol_id: 6, trait_id: 7},
  {sympol_id: 6, trait_id: 13},
  {sympol_id: 6, trait_id: 19},
  {sympol_id: 6, trait_id: 20},

  {sympol_id: 7, trait_id: 2},
  {sympol_id: 7, trait_id: 4},
  {sympol_id: 7, trait_id: 8},
  {sympol_id: 7, trait_id: 9},
  {sympol_id: 7, trait_id: 16},
  
  {sympol_id: 8, trait_id: 2},
  {sympol_id: 8, trait_id: 4},
  {sympol_id: 8, trait_id: 7},
  {sympol_id: 8, trait_id: 13},
  {sympol_id: 8, trait_id: 16},
  
  {sympol_id: 9, trait_id: 2},
  {sympol_id: 9, trait_id: 4},
  {sympol_id: 9, trait_id: 7},
  {sympol_id: 9, trait_id: 15},
  {sympol_id: 9, trait_id: 16},
  {sympol_id: 9, trait_id: 19},

  {sympol_id: 10, trait_id: 2},
  {sympol_id: 10, trait_id: 5},
  {sympol_id: 10, trait_id: 7},
  {sympol_id: 10, trait_id: 26},
  
  {sympol_id: 11, trait_id: 1},
  {sympol_id: 11, trait_id: 4},
  {sympol_id: 11, trait_id: 7},
  {sympol_id: 11, trait_id: 13},
  {sympol_id: 11, trait_id: 17},

  {sympol_id: 12, trait_id: 1},
  {sympol_id: 12, trait_id: 4},
  {sympol_id: 12, trait_id: 7},
  {sympol_id: 12, trait_id: 19},  

  {sympol_id: 13, trait_id: 2},  
  {sympol_id: 13, trait_id: 4},  
  {sympol_id: 13, trait_id: 7},  
  {sympol_id: 13, trait_id: 9},  
  {sympol_id: 13, trait_id: 18},  

  {sympol_id: 14, trait_id: 2},  
  {sympol_id: 14, trait_id: 4},  
  {sympol_id: 14, trait_id: 7},  
  {sympol_id: 14, trait_id: 13},  

  {sympol_id: 15, trait_id: 2},  
  {sympol_id: 15, trait_id: 4},  
  {sympol_id: 15, trait_id: 6},  
  
  {sympol_id: 16, trait_id: 2},  
  {sympol_id: 16, trait_id: 4},  

  {sympol_id: 17, trait_id: 2},  
  {sympol_id: 17, trait_id: 4},

  {sympol_id: 18, trait_id: 1}, 
  {sympol_id: 18, trait_id: 4}, 
  {sympol_id: 18, trait_id: 7},

  {sympol_id: 19, trait_id: 2},
  {sympol_id: 19, trait_id: 4},
  {sympol_id: 19, trait_id: 6},

  {sympol_id: 20, trait_id: 2},
  {sympol_id: 20, trait_id: 4},
  {sympol_id: 20, trait_id: 6},

  {sympol_id: 21, trait_id: 2},
  {sympol_id: 21, trait_id: 4},
  {sympol_id: 21, trait_id: 13},

  {sympol_id: 22, trait_id: 2},
  {sympol_id: 22, trait_id: 4},
  {sympol_id: 22, trait_id: 7},
  {sympol_id: 22, trait_id: 13},

  {sympol_id: 23, trait_id: 2},
  {sympol_id: 23, trait_id: 4},
  {sympol_id: 23, trait_id: 9},
  {sympol_id: 23, trait_id: 12},

  {sympol_id: 24, trait_id: 2},
  {sympol_id: 24, trait_id: 4},
  
  {sympol_id: 25, trait_id: 2},
  {sympol_id: 25, trait_id: 4},

  {sympol_id: 26, trait_id: 2},
  {sympol_id: 26, trait_id: 4},
  {sympol_id: 26, trait_id: 13},

  {sympol_id: 27, trait_id: 2},
  {sympol_id: 27, trait_id: 4},
  {sympol_id: 27, trait_id: 13},

  {sympol_id: 28, trait_id: 1},
  {sympol_id: 28, trait_id: 4},
  {sympol_id: 28, trait_id: 7},
  {sympol_id: 28, trait_id: 13},

  {sympol_id: 29, trait_id: 2},
  {sympol_id: 29, trait_id: 4},

  {sympol_id: 30, trait_id: 2},
  {sympol_id: 30, trait_id: 4},
  {sympol_id: 30, trait_id: 13},


  
  {sympol_id: 31, trait_id: 1},
  {sympol_id: 31, trait_id: 4},
  {sympol_id: 31, trait_id: 7},
  {sympol_id: 31, trait_id: 9},
  {sympol_id: 31, trait_id: 18},

  {sympol_id: 32, trait_id: 2},
  {sympol_id: 32, trait_id: 4},
  {sympol_id: 32, trait_id: 12},

  {sympol_id: 33, trait_id: 1},
  {sympol_id: 33, trait_id: 4},
  {sympol_id: 33, trait_id: 7},

  {sympol_id: 34, trait_id: 1},
  {sympol_id: 34, trait_id: 4},
  {sympol_id: 34, trait_id: 17},

  {sympol_id: 35, trait_id: 1},
  {sympol_id: 35, trait_id: 4},
  {sympol_id: 35, trait_id: 7},

  {sympol_id: 36, trait_id: 1},
  {sympol_id: 36, trait_id: 4},
  {sympol_id: 36, trait_id: 15},
  {sympol_id: 36, trait_id: 4},

  {sympol_id: 37, trait_id: 1},
  {sympol_id: 37, trait_id: 5},
  {sympol_id: 37, trait_id: 14},
  {sympol_id: 37, trait_id: 22},

  {sympol_id: 38, trait_id: 1},
  {sympol_id: 38, trait_id: 4},
  {sympol_id: 38, trait_id: 7},
  {sympol_id: 38, trait_id: 17},

  {sympol_id: 39, trait_id: 1},
  {sympol_id: 39, trait_id: 4},
  {sympol_id: 39, trait_id: 8},

  {sympol_id: 40, trait_id: 1},
  {sympol_id: 40, trait_id: 5},
  {sympol_id: 40, trait_id: 11},
  {sympol_id: 40, trait_id: 15},
  {sympol_id: 40, trait_id: 19},

  {sympol_id: 41, trait_id: 1},
  {sympol_id: 41, trait_id: 4},
  {sympol_id: 41, trait_id: 7},

  {sympol_id: 42, trait_id: 2},
  {sympol_id: 42, trait_id: 5},
  {sympol_id: 42, trait_id: 7},

  {sympol_id: 43, trait_id: 1},
  {sympol_id: 43, trait_id: 5},
  {sympol_id: 43, trait_id: 7},
  {sympol_id: 43, trait_id: 9},
  {sympol_id: 43, trait_id: 11},
  {sympol_id: 43, trait_id: 15},

  {sympol_id: 44, trait_id: 1},
  {sympol_id: 44, trait_id: 5},
  {sympol_id: 44, trait_id: 8},
  {sympol_id: 44, trait_id: 21},

  {sympol_id: 45, trait_id: 2},
  {sympol_id: 45, trait_id: 4},
  {sympol_id: 45, trait_id: 8},
  {sympol_id: 45, trait_id: 12},
  {sympol_id: 45, trait_id: 15},
  {sympol_id: 45, trait_id: 19},

  {sympol_id: 46, trait_id: 1},
  {sympol_id: 46, trait_id: 4},
  {sympol_id: 46, trait_id: 7},
  {sympol_id: 46, trait_id: 11},
  {sympol_id: 46, trait_id: 19},

  {sympol_id: 47, trait_id: 1},
  {sympol_id: 47, trait_id: 3},
  {sympol_id: 47, trait_id: 7},
  {sympol_id: 47, trait_id: 17},

  {sympol_id: 48, trait_id: 1},
  {sympol_id: 48, trait_id: 2},
  {sympol_id: 48, trait_id: 4},
  {sympol_id: 48, trait_id: 7},
  {sympol_id: 48, trait_id: 17},

  {sympol_id: 49, trait_id: 1},
  {sympol_id: 49, trait_id: 5},
  {sympol_id: 49, trait_id: 7},
  {sympol_id: 49, trait_id: 11},
  {sympol_id: 49, trait_id: 17},

  {sympol_id: 50, trait_id: 1},
  {sympol_id: 50, trait_id: 4},
  {sympol_id: 50, trait_id: 7},
  {sympol_id: 50, trait_id: 11},
  {sympol_id: 50, trait_id: 16},

  {sympol_id: 51, trait_id: 1},
  {sympol_id: 51, trait_id: 2},
  {sympol_id: 51, trait_id: 5},
  {sympol_id: 51, trait_id: 14},
  {sympol_id: 51, trait_id: 24},

  {sympol_id: 52, trait_id: 2},
  {sympol_id: 52, trait_id: 5},
  {sympol_id: 52, trait_id: 8},
  {sympol_id: 52, trait_id: 11},

  {sympol_id: 53, trait_id: 2},
  {sympol_id: 53, trait_id: 4},
  {sympol_id: 53, trait_id: 6},

  {sympol_id: 54, trait_id: 1},
  {sympol_id: 54, trait_id: 3},
  {sympol_id: 54, trait_id: 8},

  {sympol_id: 55, trait_id: 1},
  {sympol_id: 55, trait_id: 4},
  {sympol_id: 55, trait_id: 7},
  {sympol_id: 55, trait_id: 17},

  {sympol_id: 56, trait_id: 2},
  {sympol_id: 56, trait_id: 3},
  {sympol_id: 56, trait_id: 8},
  {sympol_id: 56, trait_id: 11},

  {sympol_id: 57, trait_id: 1},
  {sympol_id: 57, trait_id: 4},
  {sympol_id: 57, trait_id: 7},
  {sympol_id: 57, trait_id: 9},
  {sympol_id: 57, trait_id: 20},

  {sympol_id: 58, trait_id: 2},
  {sympol_id: 58, trait_id: 5},
  {sympol_id: 58, trait_id: 6},
  {sympol_id: 58, trait_id: 17},
  {sympol_id: 58, trait_id: 19},

  {sympol_id: 59, trait_id: 1},
  {sympol_id: 59, trait_id: 4},
  {sympol_id: 59, trait_id: 7},
  {sympol_id: 59, trait_id: 9},
  {sympol_id: 59, trait_id: 19},

  {sympol_id: 60, trait_id: 1},
  {sympol_id: 60, trait_id: 4},
  {sympol_id: 60, trait_id: 7},
  {sympol_id: 60, trait_id: 9},
  {sympol_id: 60, trait_id: 19},

  {sympol_id: 61, trait_id: 1},
  {sympol_id: 61, trait_id: 3},
  {sympol_id: 61, trait_id: 7},
  {sympol_id: 61, trait_id: 11},

  {sympol_id: 62, trait_id: 1},
  {sympol_id: 62, trait_id: 5},
  {sympol_id: 62, trait_id: 7},
  {sympol_id: 62, trait_id: 26},
  {sympol_id: 62, trait_id: 17},

  {sympol_id: 63, trait_id: 1},
  {sympol_id: 63, trait_id: 5},
  {sympol_id: 63, trait_id: 11},
  {sympol_id: 63, trait_id: 19},

  {sympol_id: 64, trait_id: 1},
  {sympol_id: 64, trait_id: 5},
  {sympol_id: 64, trait_id: 7},
  {sympol_id: 64, trait_id: 13},

  {sympol_id: 65, trait_id: 1},
  {sympol_id: 65, trait_id: 4},
  {sympol_id: 65, trait_id: 7},
  {sympol_id: 65, trait_id: 9},
  {sympol_id: 65, trait_id: 20},

  {sympol_id: 66, trait_id: 1},
  {sympol_id: 66, trait_id: 3},
  {sympol_id: 66, trait_id: 7},
  {sympol_id: 66, trait_id: 11},

  {sympol_id: 67, trait_id: 1},
  {sympol_id: 67, trait_id: 5},
  {sympol_id: 67, trait_id: 8},
  {sympol_id: 67, trait_id: 9},
  {sympol_id: 67, trait_id: 11},
  {sympol_id: 67, trait_id: 26},

  {sympol_id: 68, trait_id: 1},
  {sympol_id: 68, trait_id: 4},
  {sympol_id: 68, trait_id: 7},
  {sympol_id: 68, trait_id: 17},

  {sympol_id: 69, trait_id: 1},
  {sympol_id: 69, trait_id: 4},
  {sympol_id: 69, trait_id: 7},
  {sympol_id: 69, trait_id: 19},

  {sympol_id: 70, trait_id: 1},
  {sympol_id: 70, trait_id: 3},
  {sympol_id: 70, trait_id: 7},
  {sympol_id: 70, trait_id: 10},
  {sympol_id: 70, trait_id: 16},

  {sympol_id: 71, trait_id: 2},
  {sympol_id: 71, trait_id: 3},
  {sympol_id: 71, trait_id: 6},
  {sympol_id: 71, trait_id: 10},

  {sympol_id: 72, trait_id: 1},
  {sympol_id: 72, trait_id: 3},
  {sympol_id: 72, trait_id: 7},
  {sympol_id: 72, trait_id: 11},
  {sympol_id: 72, trait_id: 19},

  {sympol_id: 73, trait_id: 2},
  {sympol_id: 73, trait_id: 4},
  {sympol_id: 73, trait_id: 7},
  {sympol_id: 73, trait_id: 14},
  {sympol_id: 73, trait_id: 23},

  {sympol_id: 74, trait_id: 1},
  {sympol_id: 74, trait_id: 4},
  {sympol_id: 74, trait_id: 7},
  {sympol_id: 74, trait_id: 17},

  {sympol_id: 75, trait_id: 1},
  {sympol_id: 75, trait_id: 5},
  {sympol_id: 75, trait_id: 7},
  {sympol_id: 75, trait_id: 15},
  {sympol_id: 75, trait_id: 19},

  {sympol_id: 76, trait_id: 2},
  {sympol_id: 76, trait_id: 4},
  {sympol_id: 76, trait_id: 8},
  {sympol_id: 76, trait_id: 9},

  {sympol_id: 77, trait_id: 1},
  {sympol_id: 77, trait_id: 5},
  {sympol_id: 77, trait_id: 8},
  {sympol_id: 77, trait_id: 17},

  {sympol_id: 78, trait_id: 1},
  {sympol_id: 78, trait_id: 5},
  {sympol_id: 78, trait_id: 8},
  {sympol_id: 78, trait_id: 17},

  {sympol_id: 79, trait_id: 1},

  {sympol_id: 80, trait_id: 1},
  {sympol_id: 80, trait_id: 5},
  {sympol_id: 80, trait_id: 6},
  {sympol_id: 80, trait_id: 19},

  {sympol_id: 81, trait_id: 1},
  {sympol_id: 81, trait_id: 5},
  {sympol_id: 81, trait_id: 8},
  {sympol_id: 81, trait_id: 9},
  {sympol_id: 81, trait_id: 23},

  {sympol_id: 82, trait_id: 2},
  {sympol_id: 82, trait_id: 3},
  {sympol_id: 82, trait_id: 8},

  {sympol_id: 83, trait_id: 2},
  {sympol_id: 83, trait_id: 3},
  {sympol_id: 83, trait_id: 8},
  {sympol_id: 83, trait_id: 10},
  {sympol_id: 83, trait_id: 19},

  {sympol_id: 84, trait_id: 1},
  {sympol_id: 84, trait_id: 4},
  {sympol_id: 84, trait_id: 7},
  {sympol_id: 84, trait_id: 17},

  {sympol_id: 85, trait_id: 2},
  {sympol_id: 85, trait_id: 16},

  {sympol_id: 86, trait_id: 2},
  {sympol_id: 86, trait_id: 5},
  {sympol_id: 86, trait_id: 7},
  {sympol_id: 86, trait_id: 9},
  {sympol_id: 86, trait_id: 14},

  {sympol_id: 87, trait_id: 1},
  {sympol_id: 87, trait_id: 4},
  {sympol_id: 87, trait_id: 8},

  {sympol_id: 88, trait_id: 1},
  {sympol_id: 88, trait_id: 5},
  {sympol_id: 88, trait_id: 7},
  {sympol_id: 88, trait_id: 9},

  {sympol_id: 89, trait_id: 1},
  {sympol_id: 89, trait_id: 3},
  {sympol_id: 89, trait_id: 6},
  {sympol_id: 89, trait_id: 10},
  {sympol_id: 89, trait_id: 19},

  {sympol_id: 90, trait_id: 1},
  {sympol_id: 90, trait_id: 5},
  {sympol_id: 90, trait_id: 7},
  {sympol_id: 90, trait_id: 17},
  
])














